[build]
  publish = "docs/browser"
  command = "ng build --output-path docs --configuration production"
  functions = "netlify/functions"



[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true


  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200